services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt  
    startCommand: gunicorn myproject.wsgi:application  
    postDeployCommand: python manage.py migrate  
